# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CICD:
    name: Hushed-ADR
    runs-on: ubuntu-latest
    steps:
    - name: Pull request steps
      if: github.event_name == 'pull_request'
      #timeout-minutes: 20
      run: |
          ./gradlew clean build
          ./gradlew checkstyle
    - name: Push steps
      if: github.event_name == 'push'
      env:
        artifactory_user: ${{ secrets.ARTIFACTORY_USERNAME }}
        artifactory_password: ${{ secrets.ARTIFACTORY_PASSWORD }}
        artifactory_url: "https://artifactory.testing.hushed.com/artifactory"
      run: |
          ./gradlew clean build
          ./gradlew checkstyle
          ./gradlew artifactoryPublish -Partifactory_contextUrl=$artifactory_url -Partifactory_user=$artifactory_user -Partifactory_password=$artifactory_password
